### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by essenciary** [hexedpackets/trot#1]
Nice one - any plans for adding extra features for developing APIs? Things like: 
* versioning
* REST-ful resources
* nested routes

**Comment by hexedpackets** [comment]
Versioning is definitely at the top of my to-do list, I've opened #2 to track it.

Nested routes I'm a little torn on. I'm thinking of having namespaces separated at the module level, likely by adding a module attribute containing the root path. Modules could of course then be flattened or nested in the same file. Using modules for namespaces feels much more like idiomatic Elixir to me than doing something similar to Sinatra's namespace extension.

For RESTful resources, are you referring to route generation like in Phoenix (http://hexdocs.pm/phoenix/Phoenix.Router.html#resources/4) or did you have something else in mind?

**Comment by essenciary** [comment]
Module attributes surely sounds interesting. Maru has a different approach to namespaces (looks like macros but haven't checked) https://github.com/falood/maru

Restful resources: exactly that. Ideally being able to nest them and get the expected routes: 
```elixir
resources :posts do 
    resources :comments
end
```

**Comment by hexedpackets** [comment]
I don't really see the usefulness of that style of resource generation here since routes aren't separate from the functions that handle requests. Trot isn't designed to be used for an MVC style app, that use case is better suited for Phoenix.

**Comment by essenciary** [comment]
I see. I'm looking for a quick way of modeling/mocking APIs and then being able to easily turn them into production code. Phoenix seems a bit too much for building APIs but getting all the REST actions with their proper verbs in a one liner is appealing.
