### ISSUE TITLE
MatchError occurred when use plug 0.13.0

### ISSUE THREAD

**Issue by KazuCocoa** [hexedpackets/trot#16]
Hi,

When I tried https://github.com/hexedpackets/trot_example/ with `iex -S mix` then the following error occurred.

```
== Compilation error on file lib/trot_example/router/templates.ex ==
** (MatchError) no match of right hand side value: {"GET", ["compression", "pied_piper"], {:_, [], Plug.Router.Utils}, true, nil}
    lib/trot_example/router/templates.ex:5: (module)
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

I only changed version of plug in `mix.lock` to `0.13.0` which is latest version of `plug` .
https://github.com/hexedpackets/trot_example/blob/master/mix.lock#L4

Have you known this issue?

If with `0.12.2`, `trot` works well :)

**Comment by hexedpackets** [comment]
Looks like there was a change to the helper method `Plug.Router.__route__/4` in 0.13. I'll have a fix up shortly!

**Comment by KazuCocoa** [comment]
Thanks for your quick fix !

In addition, I found "(File.Error) could not read file VERSION: no such file or directory in 0.5.1 #18"
