### ISSUE TITLE
Update plug_heartbeat

### ISSUE THREAD

**Issue by whatyouhide** [hexedpackets/trot#21]
Hey, author of `plug_heartbeat` here, which you're using as a dependency. Just wanted to give a heads up to update `plug_heartbeat` to `0.2` (since you're using `~> 0.1`, a `mix deps.update plug_heartbeat` would be enough) because `0.1` breaks with older versions of Plug. This happens because of `Plug.Conn.full_path/1`, which `plug_heartbeat` was using and which was deprecated.

I noticed because of https://github.com/whatyouhide/plug_heartbeat/issues/2.

**Comment by hexedpackets** [comment]
Awesome, thanks for letting me know. I'll push up a fixed update today.
