### ISSUE TITLE
Running trot from the root of an umbrella project fails

### ISSUE THREAD

**Issue by holgergp** [hexedpackets/trot#23]
I am using trot as a small application within an umbrella project [here](https://github.com/holgergp/kvUmbrella). 
With no further [config](https://github.com/holgergp/kvUmbrella/blob/26a26e2207b96a4d7bca7e09b3b1244b9cdf7e53/apps/http_server/config/config.exs) in <code>apps/http_server/config/config.exs</code> I am able to start the httpServer from the application directory <code>mix trot.server</code> or <code>mix run --no-halt</code>and the application works fine.

If I start the application from the root of the umbrella project using  <code>mix trot.server</code>  the application starts, but incoming request fail with 

<pre>
16:36:19.701 [error] #PID<0.302.0> running HTTPServer.Router terminated
Server: localhost:8888 (http)
Request: GET /
** (exit) an exception was raised:
    ** (RuntimeError) Trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app
        (mix) lib/mix/project.ex:332: Mix.Project.app_path/1
        (mix) lib/mix/project.ex:353: Mix.Project.compile_path/1
        (mix) lib/mix/tasks/compile.elixir.ex:53: Mix.Tasks.Compile.Elixir.run/1
        (trot) lib/trot/live_reload.ex:20: Trot.LiveReload.call/2
        (http_server) lib/router.ex:1: HTTPServer.Router.plug_builder_call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
</pre>

Looking at [this](https://github.com/phoenixframework/phoenix/issues/463) I tried to disable LiveReloading in the [config.exs](https://github.com/holgergp/kvUmbrella/commit/59252bc7fe7a307868a4cc3fd4f99de8f31c82f3)

This seems to fix the issue, but sadly loosing live reload support.

**Comment by hexedpackets** [comment]
Thanks for the report! It looks like Phoenix fixed this in their code reloading by iterating through the available modules to find what to reload. I can probably do the same thing here.

**Comment by holgergp** [comment]
Ah nice! Thanks!
I looked at the Phoenix commit and tried to retrofit it myself, but as an Elixir newbie I had a hard time doing so. In particular I couldn't match some Phoenix features (e.g. `Phoenix.modules`). 
I'm curious how the solution will look like. 
Thanks again.

**Comment by holgergp** [comment]
Awesome! Thanks!
