### ISSUE TITLE
Set correct content type for JSON responses

### ISSUE THREAD

**Issue by abhin4v** [hexedpackets/trot#34]
When returning a response with JSON as the body, Trot should set the "content-type" header to "application/json". 

Right now it sets no content type and hence each request handler which returns an object must set the header too. This is cumbersome and there is no reason to do this. Also note that this functionality cannot be implemented as a post routing plug since the response is closed post routing and hence is unwritable.

**Comment by hexedpackets** [comment]
Great idea! I pushed up a change to master that sets Content-Type when encoding JSON, it will end up on hex in the next release.
